### ISSUE TITLE
Python 2 a problem / trying to integrate with Home Assistant OS

### ISSUE THREAD

**Issue by Pittermaennchen** [ThisisDennis/bring-shopping-rhasspy#1]
The code is python 2, right? Is this a problem, since there is already python 3?

I am desperately trying to get Rhasspy to edit my Bring-Grocery-List. But my Rhasspy and everything else is running on a Raspberry Pi with homeAssistant OS.

Since there is no bring-Addon I am trying to get your Code to work with pyscript. But I do not get how to achieve that.

**Comment by ThisisDennis** [comment]
Well i think it was originally written in python 2, but im running it on Python 3. So thats not the problem. I don't have enough information to help you out here. But if you have another device in the network you dont have to run on your homeAssistant OS.

**Comment by ThisisDennis** [comment]
The app communicates with rhasspy via mqtt, so you need to make sure you have the correct host and port set. In the rhasspy settings you need to set mqtt to external and in the rhasspy-hermes-app you may need to set the host. But mostly you just need to set up your Rhasspy settings under MQTT to the right target Host (where this app is running). If you need to configure the hermes-app. This should work via the app: 
`python3 action-bring.py --host YOURHOST`
try also `python3 action-bring.py --help` to get little more information
if the app is on the same device as rhasspy you normally don't need to set the host.
Check the rhasspy and rhasspy-ermes app documentation if necessary. 

[Rhasspy Hermes App](https://rhasspy-hermes-app.readthedocs.io/en/latest/usage.html)

[Rhasspy](https://rhasspy.readthedocs.io/en/latest/services/#internal-vs-external-mqtt)

I hope this helps a bit.

Short:
- go to your rhasspy settings set MQTT to external, host to your bring-"server" and port to 1883
- run the app `python3 action-bring.py` or install it as server `bash setupWithServer.sh`
- If you can get this to run, you can set up the rest (username, password etc.) in Rhasspy but dont forget to set it up in this app, too.

**Comment by Pittermaennchen** [comment]
Thank you very much for your quick response!!

Indeed I have a second Raspberry Pi (running Raspbian) as Rhasspy Satellite. So the MQTT-settings are already set.

So I cloned your Git, run the app as you told me and set the host to my HomeAssistantOS-Raspberry-IP (where my MQTT-Broker runs on). 

After the debug-log showed a succesful subscription to the topic I asked Rhasspy to add something to my bring-list, resulting in the wanted "Philipp:addItem_bringshop"-Intent. But still no new added article on my bring-list. :(

Please see the debug-log from the action-bring.py app:

> python3 action-bring.py --host=XXX.XXX.XXX.XX --username=XXXXXXX --password=XXXXXXXXXXXX --debug
> [DEBUG:2022-11-08 23:34:13,147] HermesApp: Namespace(host='XXX', port=1883, username='XXX', password='XXX', tls=False, tls_ca_certs=None, tls_certfile=None, tls_keyfile=None, tls_cert_reqs='CERT_REQUIRED', tls_version=None, tls_ciphers=None, site_id=None, debug=True, log_format='[%(levelname)s:%(asctime)s] %(name)s: %(message)s')
> [DEBUG:2022-11-08 23:34:13,150] asyncio: Using selector: EpollSelector
> [DEBUG:2022-11-08 23:34:13,156] HermesApp: Connecting to XXX.XXX:1883
> [DEBUG:2022-11-08 23:34:13,163] asyncio: Using selector: EpollSelector
> [DEBUG:2022-11-08 23:34:13,166] BringApp: Connected to MQTT broker
> [DEBUG:2022-11-08 23:34:13,167] BringApp: Subscribed to hermes/intent/Philipp:addItem_bringshop
> [DEBUG:2022-11-08 23:34:13,168] BringApp: Subscribed to hermes/intent/Philipp:readList_bringshop
> [DEBUG:2022-11-08 23:34:13,169] BringApp: Subscribed to hermes/intent/Philipp:deleteItem_bringshop
> [DEBUG:2022-11-08 23:34:13,170] BringApp: Subscribed to hermes/intent/Philipp:checkList_bringshop
> [ERROR:2022-11-08 23:34:43,971] HermesApp: on_raw_message
> Traceback (most recent call last):
>   File "/home/pi/.local/lib/python3.9/site-packages/rhasspyhermes_app/__init__.py", line 208, in on_raw_message
>     nlu_intent = NluIntent.from_json(payload)
>   File "/home/pi/.local/lib/python3.9/site-packages/dataclasses_json/api.py", line 72, in from_json
>     kvs = json.loads(s,
>   File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
>     return cls(**kw).decode(s)
> TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by ThisisDennis** [comment]
Hi,
it looks like the rhasspy-hermes version is to old for your bullseye OS or Python 3.9
Try
` pip3 install --upgrade rhasspy-hermes` 
or
` pip install --upgrade rhasspy-hermes` 

or remove the "venv"-folder and run `bash setup.sh`
Tell me if it works.

**Comment by Pittermaennchen** [comment]
Hi, thank you! I was busy with work today and could try that only just now.

This is the result of pip3 install --upgrade rhasspy-hermes. An error occured, I bolded it here:

> :~ $ pip3 install --upgrade rhasspy-hermes
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: rhasspy-hermes in ./.local/lib/python3.9/site-packages (0.6.1)
Collecting rhasspy-hermes
  Using cached https://www.piwheels.org/simple/rhasspy-hermes/rhasspy_hermes-0.6.2-py3-none-any.whl (39 kB)
Requirement already satisfied: paho-mqtt==1.5.0 in ./.local/lib/python3.9/site-packages (from rhasspy-hermes) (1.5.0)
Collecting dataclasses-json==0.5.6
  Using cached https://www.piwheels.org/simple/dataclasses-json/dataclasses_json-0.5.6-py3-none-any.whl (25 kB)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in ./.local/lib/python3.9/site-packages (from dataclasses-json==0.5.6->rhasspy-hermes) (3.18.0)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in ./.local/lib/python3.9/site-packages (from dataclasses-json==0.5.6->rhasspy-hermes) (1.5.1)
Requirement already satisfied: typing-inspect>=0.4.0 in ./.local/lib/python3.9/site-packages (from dataclasses-json==0.5.6->rhasspy-hermes) (0.8.0)
Requirement already satisfied: packaging>=17.0 in ./.local/lib/python3.9/site-packages (from marshmallow<4.0.0,>=3.3.0->dataclasses-json==0.5.6->rhasspy-hermes) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.local/lib/python3.9/site-packages (from packaging>=17.0->marshmallow<4.0.0,>=3.3.0->dataclasses-json==0.5.6->rhasspy-hermes) (3.0.9)
Requirement already satisfied: typing-extensions>=3.7.4 in ./.local/lib/python3.9/site-packages (from typing-inspect>=0.4.0->dataclasses-json==0.5.6->rhasspy-hermes) (4.4.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./.local/lib/python3.9/site-packages (from typing-inspect>=0.4.0->dataclasses-json==0.5.6->rhasspy-hermes) (0.4.3)
Installing collected packages: dataclasses-json, rhasspy-hermes
  Attempting uninstall: dataclasses-json
    Found existing installation: dataclasses-json 0.4.2
    Uninstalling dataclasses-json-0.4.2:
      Successfully uninstalled dataclasses-json-0.4.2
  Attempting uninstall: rhasspy-hermes
    Found existing installation: rhasspy-hermes 0.6.1
    Uninstalling rhasspy-hermes-0.6.1:
      Successfully uninstalled rhasspy-hermes-0.6.1
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rhasspy-hermes-app 1.1.2 requires rhasspy-hermes==0.6.1, but you have rhasspy-hermes 0.6.2 which is incompatible.**
Successfully installed dataclasses-json-0.5.6 rhasspy-hermes-0.6.2

**Comment by Pittermaennchen** [comment]
But it worked!!! Thank you!!!

Just tried out to add something to my bring list, and it magically happened!

(I don't know if that made the difference, but I ran the command multiple times, then also 
`pip3 install --upgrade rhasspy-hermes-app`
without knowing if that is even a thing.

And then I changed to the bring-shopping-rhasspy-folder and ran `pip3 install --upgrade rhasspy-hermes` again.

Anyway: it works now, thank you!! That's awesome :)

**Comment by ThisisDennis** [comment]
Cool. I am glad that I could help. I think you only had to upgrade rhasspy-hermes-app, they changed it already. The problem was the old version in my repo. But feel free to update my shopping items etc.. would be cool to have a bigger, cleaner version of it.

**Comment by Pittermaennchen** [comment]
I will try! Right now I am struggling because Rhasspy always mixes in a lot of words from the weather-slot. Therefore it does not recognize my bring- and other intents at all. Thats pretty odd, because _**some**_ other intents are recognized pretty well.
